export const DATA_PRODUCTS = [
  {
    id: "msme-10k",
    title: "10,000 MSME Database",
    category: "MSME Data",
    handle: "10-000-msme-database",
    appPath: "/app/tenmsme",
    carouselImage: "/10k.webp",
    records: "10,000",
    percentOff: 80,
    cutPrice:5000,
    price:999,
  },
  {
    id: "msme-20k",
    title: "20,000 MSME Database",
    category: "MSME Data",
    handle: "20-000-msme-database",
    appPath: "/app/twentymsme",
    carouselImage: "/20k.webp",
    records: "20,000",
    percentOff: 82,
    cutPrice:10000,
    price:1800,
  },
  {
    id: "msme-30k",
    title: "30,000 MSME Database",
    category: "MSME Data",
    handle: "30-000-msme-database",
    appPath: "/app/thirtymsme",
    carouselImage: "/30k.webp",
    records: "30,000",
    percentOff: 82,
    cutPrice:15000,
    price:2700,
  },
  {
    id: "msme-40k",
    title: "40,000 MSME Database",
    category: "MSME Data",
    handle: "40-000-msme-database",
    appPath: "/app/fortymsme",
    carouselImage: "/40k.webp",
    records: "40,000",
    percentOff: 82,
    cutPrice:20000,
    price:3600,
  },
  {
    id: "angel-500",
    title: "Top 500 Angel Investor Data (India, USA, UAE)",
    category: "Investor Data",
    handle: "top-500-angel-investor-data-india-usa-uae",
    appPath: "/app/angel-investor",
    carouselImage: "/500_angel.webp",
    records: "500",
    percentOff: 80,
    cutPrice:5000,
    price:1000,
  },
  {
    id: "vc-250",
    title: "Top 250+ VC & Angel Investors (India)",
    category: "Investor Data",
    handle: "top-250-vc-angels-investor-india",
    appPath: "/app/vc-angel-investor",
    carouselImage: "/250_plus.webp",
    records: "250+",
    percentOff: 80,
    cutPrice:2500,
    price:500,
  },
  {
    id: "550-logistics",
    title: "550 Logistics & Freight Agents",
    category: "Logistics Data",
    handle: "550-logistics-and-freight-agents",
    appPath: "/app/logistics-freight",
    carouselImage: "/550_logistics.webp",
    records: "550",
    percentOff: 49,
    cutPrice:1375,
    price:699,
  },
  {
    id: "8800-packaging",
    title: "8,800 Packaging Industry Database",
    category: "Packaging Data",
    handle: "8800-packaging-industry",
    appPath: "/app/packaging",
    carouselImage: "/8800_packaging.webp",
    records: "8,800",
    percentOff: 75,
    cutPrice:4400,
    price:1099,
  },
  {
    id: "chemicals-industry",
    title: "16,000+ Chemicals Industry Database",
    category: "Chemicals Industry Data",
    handle: "chemical-industry-database",
    appPath: "/app/chemicals-industry",
    carouselImage: "/chemical_industry.webp",
    records: "16,000+",
    percentOff: 80,
    cutPrice:8000,
    price:1600,
  },
  {
    id: "building-construction",
    title: "13,500 Building & Construction Materials Database",
    category: "Building & Construction Data",
    handle: "building-construction-materials-database",
    appPath: "/app/building-construction",
    carouselImage: "/construction.webp",
    records: "13,500",
    percentOff: 80,
    cutPrice:6750,
    price:1350,
  },
  {
    id: "electrical-industry",
    title: "18,000+ Electrical & Electronics Industry Database",
    category: "Electrical & Electronics Data",
    handle: "electrical-electronics-industry-database",
    appPath: "/app/electrical-industry",
    carouselImage: "/electrical_industry.webp",
    records: "18,000+",
    percentOff: 80,
    cutPrice:9000,
    price:1800,
  },
  {
    id: "gems-jewelry",
    title: "7,000+ Gems & Jewelry Database",
    category: "Gems & Jewelry Data",
    handle: "gems-jewelry-database",
    appPath: "/app/gems-jewelry",
    carouselImage: "/gems_jewelry.webp",
    records: "7,000+",
    percentOff: 70,
    cutPrice:3500,
    price:1050,
  },
  {
    id: "gifts-handcrafts",
    title: "15,000 Gifts & Handicrafts Companies",
    category: "Gifts & Handicrafts Data",
    handle: "gifts-handicrafts-companies",
    appPath: "/app/gifts-handcrafts",
    carouselImage: "/gifts_handcrafts.webp",
    records: "15,000",
    percentOff: 70,
    cutPrice:7500,
    price:2250,
  },
  {
    id: "computer-it",
    title: "4,000 Computer & IT Industry Database",
    category: "Computer & IT Data",
    handle: "computer-it-industry-database",
    appPath: "/app/computer-it",
    carouselImage: "/computer_it.webp",
    records: "4,000",
    percentOff: 70,
    cutPrice:2000,
    price:600,
  },
  {
    id: "minerals-metals",
    title: "12,900 Minerals & Metals Database",
    category: "Minerals & Metals Data",
    handle: "12-900-minerals-metals-database",
    appPath: "/app/minerals-metals",
    carouselImage: "/minerals_metals.webp",
    records: "12,900",
    percentOff: 80,
    cutPrice:6450,
    price:1290,
  },
  {
    id: "textile-leather",
    title: "18,500+ Textile & Leather Companies Database",
    category: "Textile & Leather Data",
    handle: "18-500-textile-leather-companies-database",
    appPath: "/app/textile-leather",
    carouselImage: "/textile_leather.webp",
    records: "18,500+",
    percentOff: 70,
    cutPrice:9250,
    price:2775,
  },
  {
    id: "automobile",
    title: "9,000 Automobile Companies Database",
    category: "Automotive Data",
    handle: "9-000-automobile-companies-database",
    appPath: "/app/automobile",
    carouselImage: "/automobile.webp",
    records: "9,000",
    percentOff: 80,
    cutPrice:4500,
    price:900,
  },
  {
    id: "industrial-machinery",
    title: "25,000 Industrial Machinery & Tools Database",
    category: "Industrial Data",
    handle: "industrial-machinery-tools-database",
    appPath: "/app/industrial-machinery",
    carouselImage: "/industrial_machinery.webp",
    records: "25,000",
    percentOff: 80,
    cutPrice:12500,
    price:2500,
  },
];

export function productUrl(storefrontBaseUrl, handle) {
  const base = (storefrontBaseUrl || "").replace(/\/$/, "");
  if (!base) return "#";
  return `${base}/products/${handle}`;
}

/** Catalog entries for “other products” carousels (excludes the page you’re on). */
export function otherDatabaseProducts(excludeId) {
  return DATA_PRODUCTS.filter((p) => p.id !== excludeId);
}
